'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

def gen_fibonacci(max)
	fib = Array(1..2)
	continue = true
	while continue
		length = fib.length
		sum = fib.at(length - 1) + fib.at(length - 2)
		if sum < max
			fib.push(sum)
		else
			continue = false
		end
	end
	return fib
end

def get_evens(fib_sequence)
	sum = 0
	for int in fib_sequence
		if int % 2 == 0
			sum = sum + int
		end
	end
	return sum
end

print "Enter a number: "
max = gets.chomp.to_i
sequence = gen_fibonacci(max)
sum_evens = get_evens(sequence)
puts "The sum of even numbers in the fibonacci sequence of values less than #{max} is #{sum_evens}"